# Generated by Django 4.2.21 on 2025-06-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
