# Generated by Django 4.2.21 on 2025-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_number',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
