# Generated by Django 4.2.21 on 2025-06-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle_title', models.CharField(max_length=255)),
                ('raffle_description', models.CharField(max_length=255)),
                ('raffle_fecha', models.DateField()),
                ('raffle_price', models.IntegerField()),
                ('raffle_image', models.ImageField(blank=True, null=True, upload_to='raffle_images/')),
            ],
        ),
    ]
